---
deployment:
  tasks:
    - export: source: /
      target: $HOME/public_html
      excludes:
        - .git/
        - node_modules/
        - .gitignore
        - README.md
        - README-AMBIENTE.md
        - GUIA-HOSPEDAGEM.md
        - preparar-hospedagem.bat
        - *.bat
        - *.ps1
        - *.py
        - .bolt/
        - .vscode/
        - dist.zip
    - export: source: /dist
      target: $HOME/public_html
      excludes:
        - .git/
        - node_modules/
